x-opencode-base: &opencode-base
  build:
    context: .
  user: opencode
  entrypoint: ["opencode"]
  volumes:
    - opencode_home:/home/opencode

services:
  opencode-tui:
    <<: *opencode-base

  opencode-server:
    <<: *opencode-base
    command: ["serve", "--hostname", "0.0.0.0", "--port", "4096"]
    ports:
      - "4096:4096"
    restart: unless-stopped

volumes:
  opencode_home:
