services:
    postgres:
      image: postgres:latest
      hostname: ${phostname:-postgres}
      pull_policy: ${pull_policy:-missing}
      restart: ${restart:-always}
      environment:
        - POSTGRES_USER=${DB_USER:-dbuser}
        - POSTGRES_PASSWORD=${DB_PASSWORD:-ZDBkODgwYz}
        - POSTGRES_DB=${DB_NAME:-n8n}
      volumes:
        - ./init:/docker-entrypoint-initdb.d:ro
        - postgres_data:/var/lib/postgresql/data
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      healthcheck:
        test: ['CMD-SHELL', 'pg_isready -h localhost -U user -d ${DB_NAME:-n8n}']
        start_period: 5s
        interval: 5s
        timeout: 5s
        retries: 10

volumes:
  postgres_data: