services:
    postgres:
      image: postgres:latest
      hostname: ${phostname}
      container_name: ${phostname}
      pull_policy: ${pull_policy:-missing}
      restart: ${restart}
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - ./init:/docker-entrypoint-initdb.d:ro
        - ./postgres:/var/lib/postgresql/data
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      healthcheck:
        test: ['CMD-SHELL', 'pg_isready -h localhost -U user -d ${POSTGRES_DB}']
        start_period: 5s
        interval: 5s
        timeout: 5s
        retries: 10

